import React from 'react';
import ReactDOM from 'react-dom';
import './index.css';
import 'css/loading.css';
import 'css/general.css';
import 'css/colors.css';
import 'css/home.css';
import 'css/settings.css';
import 'css/main.css';
import 'css/canvas.css';
import 'css/dropdown.css';
import 'css/form.css';
import 'css/timeOptionSelect.css';
import 'css/bottomPanel.css';
import 'css/dateNavigation.css';
import 'css/timelineDisplaySelect.css';
import 'css/optionsPanel.css';
import 'css/dateSelect.css';
import 'css/timeline.css';
import 'css/topPanel.css';
import 'css/graphDisplaySelect.css';
import 'css/blobs.css';
import 'css/keyboardShortcut.css';
import 'css/loginSignUp.css';
import 'css/colorSelect.css';
import 'css/queries.css';

import App from './App';

ReactDOM.render(<App />, document.getElementById('root'));
