import React from "react";
import * as ReactDOMClient from 'react-dom/client';
import "./index.css";
import "css/blobs.css";
import "css/bottomPanel.css";
import "css/colorSelect.css";
import "css/colors.css";
import "css/dateNavigation.css";
import "css/dateSelect.css";
import "css/dropdown.css";
import "css/elementsTimeline.css";
import "css/form.css";
import "css/general.css";
import "css/graphDisplaySelect.css";
import "css/home.css";
import "css/keyboardShortcut.css";
import "css/loading.css";
import "css/loginSignUp.css";
import "css/main.css";
import "css/monthChart.css";
import "css/optionsPanel.css";
import "css/queries.css";
import "css/moneyControl.css";
import "css/scrollingTimeline.css";
import "css/settings.css";
import "css/timeOptionSelect.css";
import "css/timelineDisplaySelect.css";
import "css/topPageText.css";
import "css/topPanel.css";

import App from "./App";

const container = document.getElementById('root');
const root = ReactDOMClient.createRoot(container);
root.render(<App tab="home" />);
